manifest:
  remotes:
    - name: konnko
      url-base: https://github.com/Konnko
  projects:
    - name: zmk
      remote: konnko
      revision: niceview-layer-batch
      import: app/west.yml
  self:
    path: config
